const Employee=[
    {
        id:"1",
        Name:"divya",
        Gender:"Female",
        Salary:"27889",
        DOB:"2001-08-02",
        Department:"Sales"
    },
    {
        id:"2",
        Name:"yamini",
        Gender:"Female",
        Salary:"10099",
        DOB:"2000-05-21",
        Department:"HR"
    },
    {
        id:"3",
        Name:"pooja",
        Gender:"Female",
        Salary:"18889",
        DOB:"1999-04-18", 
        Department:"Accounts"
    },
    {
        id:"4",
        Name:"sandy",
        Gender:"Male",
        Salary:"29989",
        DOB:"2003-03-11",
        Department:"Sales"
    },
    {
        id:"5",
        Name:"janu",
        Gender:"Female",
        Salary:"270889",
        DOB:"1990-11-18",
        Department:"HR"
    },
    {
        id:"6",
        Name:"depika",
        Gender:"Female",
        Salary:"127889",
        DOB:"1999-12-17",
        Department:"Sales"
    },
    {
        id:"7",
        Name:"bhanu",
        Gender:"Male",
        Salary:"98977",
        DOB:"1912-12-12",
        Department:"Accounts"
    },
]

export default Employee;
